# Generated by Django 3.2.6 on 2021-08-30 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210829_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khaosat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dienthoai', models.CharField(max_length=15)),
                ('thon', models.CharField(max_length=50)),
                ('xa', models.CharField(max_length=50)),
                ('huyen', models.CharField(max_length=50)),
                ('tinh', models.CharField(max_length=50)),
                ('diaban', models.CharField(choices=[('1', 'Đồng bằng'), ('2', 'Ven biển'), ('3', 'Trung du'), ('4', 'Miền núi – hải đảo')], max_length=1)),
                ('gioitinh', models.CharField(choices=[('0', 'Nữ'), ('1', 'Nam')], max_length=1)),
                ('dantoc', models.CharField(choices=[('0', 'Kinh'), ('1', 'Khác')], max_length=1)),
                ('tuoi', models.IntegerField(default=0)),
                ('hocvan', models.CharField(choices=[('1', 'Chưa đi học'), ('2', 'Tiểu học'), ('3', 'THCS'), ('4', 'THPT - BTPT')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 14, 50, 44, 250088)),
        ),
    ]
