# Generated by Django 3.2.6 on 2021-09-01 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210901_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khaosat',
            name='cau1a1',
            field=models.IntegerField(choices=[(1, 'Không có quyền ra quyết định'), (2, 'Cùng ra quyết định với một người khác không phải là thành viên gia đình'), (3, 'Cùng ra quyết định với một thành viên trong gia đình'), (4, 'Vợ chồng cùng ra quyết định'), (5, 'Tự mình ra quyết định')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau1a2',
            field=models.IntegerField(choices=[(1, 'Rất không tự tin'), (2, 'Không tự tin'), (3, 'Bình thường'), (4, 'Khá tự tin'), (5, 'Rất tự tin')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau1b1',
            field=models.IntegerField(choices=[(1, 'Không có quyền ra quyết định'), (2, 'Cùng ra quyết định với một người khác không phải là thành viên gia đình'), (3, 'Cùng ra quyết định với một thành viên trong gia đình'), (4, 'Vợ chồng cùng ra quyết định'), (5, 'Tự mình ra quyết định')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau1b2',
            field=models.IntegerField(choices=[(1, 'Rất không tự tin'), (2, 'Không tự tin'), (3, 'Bình thường'), (4, 'Khá tự tin'), (5, 'Rất tự tin')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau1c1',
            field=models.IntegerField(choices=[(1, 'Không có quyền ra quyết định'), (2, 'Cùng ra quyết định với một người khác không phải là thành viên gia đình'), (3, 'Cùng ra quyết định với một thành viên trong gia đình'), (4, 'Vợ chồng cùng ra quyết định'), (5, 'Tự mình ra quyết định')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau1c2',
            field=models.IntegerField(choices=[(1, 'Rất không tự tin'), (2, 'Không tự tin'), (3, 'Bình thường'), (4, 'Khá tự tin'), (5, 'Rất tự tin')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau2a',
            field=models.IntegerField(choices=[(1, 'Không có quyền ra sở hữu'), (2, 'Cùng sở hữu với một người khác không phải là thành viên gia đình'), (3, 'Cùng sở hữu với một thành viên trong gia đình'), (4, 'Vợ chồng cùng sở hữu'), (5, 'Sở hữu một mình')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='cau2b',
            field=models.IntegerField(choices=[(1, 'Không có quyền ra sở hữu'), (2, 'Cùng sở hữu với một người khác không phải là thành viên gia đình'), (3, 'Cùng sở hữu với một thành viên trong gia đình'), (4, 'Vợ chồng cùng sở hữu'), (5, 'Sở hữu một mình')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='dantoc',
            field=models.IntegerField(choices=[(0, 'Kinh'), (1, 'Khác')], default=0),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='diaban',
            field=models.IntegerField(choices=[(1, 'Đồng bằng'), (2, 'Ven biển'), (3, 'Trung du'), (4, 'Miền núi – hải đảo')], default=1),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='gioitinh',
            field=models.IntegerField(choices=[(0, 'Nữ'), (1, 'Nam')], default=0),
        ),
        migrations.AlterField(
            model_name='khaosat',
            name='hocvan',
            field=models.IntegerField(choices=[(1, 'Chưa đi học'), (2, 'Tiểu học'), (3, 'THCS'), (4, 'THPT - BTPT')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 16, 45, 51, 478638)),
        ),
    ]
